### PR TITLE
Fix renewal dates

### LINKED ISSUE #78: Cloud > LXD: resources box at the bottom of page not rendering correctly [IE9, Win 7]
It shows two small rounded corners, shadowed boxes one at the top left and another bottom left of the space. The second one is covering the text. All of the text is orange and the resource type is not all caps.

This is an issue across the site on resources box.

Looks OK on live site.

### PR DESCRIPTION
**Pull request by albertkol**
## Done

- Use `renewal.newContractStart` to display the continue from date in the modal 

## QA

- Have a renewal (ask Albert for help)
- Go to  https://ubuntu-com-10040.demos.haus/advantage?test_backend=true
- Press the Renewal button, look at the start date, should be the `renewal.newContractDate`.

## Issue / Card

Fixes #78

### CODE REVIEW

File: static/js/src/advantage/set-modal-info.js [hunk 1]
```diff
@@ -189,8 +189,14 @@ export function getPaymentInformation(paymentMethod) {
...
 
 export function getRenewalInformation(data) {
-  const startDate = new Date(data.renewalStart);
-  const endDate = new Date(data.renewalEnd);
+  const current = new Date();
+  let startDate = current;
+
+  if (current > startDate) {
+    startDate = new Date(data.newContractStart);
+  }
```
Comment (ClementChaumel) [inline static/js/src/advantage/set-modal-info.js:197]:
```suggestion
  const startDate = current > startDate ? new Date(data.newContractStart) : new Date();
```
[Ternary](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) baby!

**Review by ClementChaumel — APPROVED** [review]

**Comment by ClementChaumel** [comment]
Is that the thing you made me QA in Mattermost the other day? If so, QA +1
